### PR TITLE
Add Travis CI Support

### PR DESCRIPTION
**Pull request by kylemanna**
Travis CI will provide a simple automated mechanism to run the unit tests to make sure every pull requests works as expected on a matrix of compilers and python releases.

This is my first stab at making it work.  My repo's builds are @ https://travis-ci.org/kylemanna/nanopb

A Travis CI account will need to be setup for the main nanopb repository.

Related to #169

### CODE REVIEW

**Comment by kylemanna** [comment]
Also worth noting that it may be possible to cross compile and run in qemu for a platform like ARM.

**Comment by PetteriAimonen** [comment]
Hmm, interesting, I didn't know that Travis CI provides free build services.

I have my own Jenkins server currently, but having automated checks for pull requests would not be a bad idea.

**Comment by mhaberler** [comment]
Travis builds: out of the box - Ubuntu 14 x86_64 only
There seems to be a way to use Docker for other environments which I have not explored yet

**Comment by kylemanna** [comment]
Some more commits to polish it up.  In my integration branch everything builds:

https://travis-ci.org/kylemanna/nanopb/builds/81437431

This is a merge of the python3 branch, travis-ci branch and a fix for gcc-5 support in my misc branch.

**Comment by PetteriAimonen** [comment]
Hmm, this has worked very nicely for a few years now.. except today :)

@kylemanna, Are you interested in helping find out why it is failing now?

https://travis-ci.org/nanopb/nanopb

Python2.7 builds pass but Python3.4 builds fail due protobuf python package failing to import. By diffing from previous working build, it looks like Ubuntu has been upgraded from 12.04.5 to 14.04.5, and Python has been upgraded from 3.4.2 to 3.4.6. But the protobuf build seems to complete ok.

Is there any nicer way for running test commands in the buildroot than making a temp repo and modifying the build script there?

**Comment by kylemanna** [comment]
See PR #283 for fix.

**Pull request merged**
