### PR TITLE
grpc: implementation of grpc using nanopb

### PR DESCRIPTION
**Pull request by d21d3q**
This branch implements grpc mentioned in this [issue](https://github.com/nanopb/nanopb/issues/235).
For now it contains concept of server side decoding/encoding and working network_example.

### CODE REVIEW

**Comment by d21d3q** [comment]
Ups, now I realised that I am merging it into master... Can you create separate branch for it `dev-grpc`?

**Comment by PetteriAimonen** [comment]
Sure, I'll look into merging it into the 0.4.0 dev branch that I'll start once 0.3.8 is out.

**Comment by d21d3q** [comment]
Pleas let me know when you will be about to pull that code. I've changed a lot in order to implement non blocking parsing and server side streaming. Since I can push only to master I won't create pull requests for now.

**Comment by PetteriAimonen** [comment]
I'm quite busy currently so I'm afraid it might be a few weeks until I have time to review all this.

**Comment by bright-pan** [comment]
nice job，how can i use it？ @d21d3q

**Comment by bright-pan** [comment]
@PetteriAimonen review the PR？

**Comment by d21d3q** [comment]
@bright-pan You can see example how to use server side parsing, but since this PR I've changed lot of things ([my repo](https://github.com/d21d3q/nanopb/tree/dev-grpc) would me more actual) so that I will create another one when it will be more "mature" but currently I am busy with work on some other stuff. As soon as I will have more spare time I will continue to develop it ;)

**Comment by PetteriAimonen** [comment]
@bright-pan Sorry, I have no time currently and not sure when I will. Might be months..

**Comment by glerchundi** [comment]
@d21d3q I would like to know why did you decided to do in this way instead of relying on the http2 framing format. I think it's feasible to create a possible solution based on `nghttp2` and a your `nanogrpc`.

**Comment by d21d3q** [comment]
In order to make simple (possible?) embedding on microcontrollers (like Arduino), and have it written in C.

'nghttp2' is C++, it wouldn't fit in µC memory, it depends on `boost` -> it needs to run on some OS, and needs whole OSI model stack... 

So if not using http librrary, using http frame format would requres writing parser (and we have already parser in `nanopb`) 

One more important thing is data size. While sending data over serial connection with speed 9600 bps you don't want to have such overhead. Or while sending packet over radio (IoT here: LoRaWAN has [limitation](https://www.thethingsnetwork.org/forum/t/limitations-data-rate-packet-size-30-seconds-uplink-and-10-messages-downlink-per-day-fair-access-policy/1300) of 222 bytes per packet. And nothing like TCP (more overhead))

What would be your usecase?

**Comment by glerchundi** [comment]
> 'nghttp2' is C++, it wouldn't fit in µC memory, it depends on boost -> it needs to run on some OS, and needs whole OSI model stack...

In this case you'll be interested in the http2 frame parser which is written in C and as stated in the programming-guide documentation:

```
The most notable point in nghttp2 library architecture is it does not perform any I/O. nghttp2 only performs HTTP/2 protocol stuff based on input byte strings. It will calls callback functions set by applications while processing input. The output of nghttp2 is just byte string. An application is responsible to send these output to the remote peer. The callback functions may be called while producing output.
```

> So if not using http librrary, using http frame format would requres writing parser (and we have already parser in nanopb)

Using `nghttp2` is still valid. Take a look to the ref https://nghttp2.org/documentation/apiref.html 

> One more important thing is data size. While sending data over serial connection with speed 9600 bps you don't want to have such overhead.

HTTP2 doesn't impose much overhead due to how its designed (using HPACK for header compression) as well as its binary nature.

> Or while sending packet over radio (IoT here: LoRaWAN has limitation of 222 bytes per packet. And nothing like TCP (more overhead))

You can set the frame size in HTTP2 easily by sending the very first [SETTINGS](http://httpwg.org/specs/rfc7540.html#rfc.section.6.5) frame with your desired size in [`SETTINGS_MAX_FRAME_SIZE`](http://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_FRAME_SIZE)

WDYT?

In case you were interested on the hows take a look at this: https://github.com/glerchundi/grpc-boomerang.

**Comment by glerchundi** [comment]
Just to make more concretions on the topic:
* Disable HPACK in case is "too much" for the µC setting state size `SETTINGS_HEADER_TABLE_SIZE` to zero.
* Disable concurrent streams by settings [`SETTINGS_MAX_CONCURRENT_STREAMS`](http://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_CONCURRENT_STREAMS) to 1.

**Comment by d21d3q** [comment]
Then let's give a try :)
I'll dive into it in beginning of next year

**Comment by glerchundi** [comment]
Cool @d21d3q!

I'll try to get into this once I find a free slot. Maybe I can shed some light on the inner details about how the wire/raw packets flow.

The direct benefits of this would be:
* **Wire-compatibility with the current gRPC implementations!**: Would require some changes to bypass connection establishment and use the desired data pipe but it's not something it cannot be done. In Go it's already done by using a pre-established `net.Conn` as you can see [here](https://github.com/glerchundi/grpc-boomerang/blob/c2bbe9c8cbc8f19644b9959846d322457a242de2/cmd/websocket-server-grpc-client/main.go#L106-L108).
* In case it's supported by the server, multiple streams (which means multiple ongoing requests) multiplexed on the same data pipe.

Thanks for taking my comments in consideration.

**Comment by glerchundi** [comment]
Ok, so I get a little bit deeper and came across to these frames:

It's based on this spec:

```
message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string message = 1;
}

service Api {
  rpc Hello(HelloRequest) return (HelloResponse);
}
```

```
Wire data [Length(24) Type(8) Flags(8) R(1) StreamID(31) Frame(0..Length)]

Init + Settings negotiation

-> 24: 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
	-> PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n
<- 9: 000000 04 00 00000000
      SETTINGS
-> 9: 000000 04 01 00000000
      SETTINGS (ACK = 0x01)
-> 9: 000000 04 00 00000000
      SETTINGS
<- 9: 000000 04 01 00000000
      SETTINGS (ACK = 0x01)

Call

-> 58: 000031 01 04 00000001      
       HPACK[83864588621accc632d141ff815f8b1d
             75d0620d263d4c4d65647a8a9acac8b4
             c7602bbab87f40027465864d833505b11f]
       HEADERS (END_HEADERS = 0x04)
         :method: POST
         :scheme: http
         :path: /Api/Hello
         :authority: 
         content-type: application/grpc
         user-agent: grpc-go/1.7.1
         te: trailers

-> 21: 00000c 00 01 00000001
      [00 00000007 0a05476f726b61] compression(1) size(4) proto(size)
       DATA (END_STREAM = 0x01)
         proto3_decode(message HelloRequest{string name=1},0a05476f726b61)
           name:"Gorka"

<- 30: 000004 08 00 00000000 0000000c
       WINDOW_UPDATE = +12
       000008 06 00 00000000 02041010090e0707
       PING

-> 17: 000008 06 01 00000000 02041010090e0707
       PING (ACK)
       
-> 30: 000004 08 00 00000000 00000012
       WINDOW_UPDATE = +18
       000008 06 00 00000000 02041010090e0707
       PING

<- 17: 000008 06 01 00000000 02041010090e0707
       PING (ACK)

<- 50: 00000e 01 04 00000001 HPACK[885f8b1d75d0620d263d4c4d6564]
       HEADERS (END_HEADERS = 0x04)
         :status: 200
         content-type: application/grpc

       000012 00 00 00000001 
       [00 0000000d 0a0b48656c6c6f20476f726b61]
       DATA
         proto3_decode(message HelloResponse{string msg=1},0a0b48656c6c6f20476f726b61)
           msg:"Hello Gorka"
       
<- 33: 000018 01 05 00000001 40889acac8b21234da8f013040899acac8b5254207317f00
       HEADERS (END_STREAM = 0x01 | END_HEADERS = 0x04)
         hpack_decode(4088...)
           grpc-status: 0
           grpc-message:
```

For a Hello(HelloRequest(name="Gorka)) = HelloResponse(message="Hello Gorka") request:
- Client sends **166** bytes.
- Server sends **148** bytes.

Unavoidable things:
- Magic init string (24 bytes)
- `SETTINGS` to negotiate data pipe possibilities
- `HEADERS` + `DATA` frames

We can check if there is a real possibility to:
- Avoid `WINDOW_UPDATE` frames on both sides, and in case it's not possible disable just on the server side.
- Avoid `PING` frames. In this example I used gRPC-Go which uses PING frames to calculate the latency and in case it doesn't comply with the context timeout it forcibly closes it.

WDYT?

**Comment by d21d3q** [comment]
I would start from writing minimal program for Arduino - if it fit in memory. It could be client example but sending data over Serial. If it fits on memory, then on PC run some program that will transfer serial data to some socket and back to check if it works.

**Comment by d21d3q** [comment]
I would start from writing minimal program for Arduino - if it fit in memory. It could be client example but sending data over Serial. If it fits on memory, then on PC run some program that will transfer serial data to some socket and back to check if it works.

**Comment by glerchundi** [comment]
@d21d3q @PetteriAimonen some current status updates:

Obviously this would be 'completely' useless in case there wasn't the possibility to use custom data pipes from the core libraries (c, go, java). I opened an issue in the grpc mailing list:

https://groups.google.com/forum/#!msg/grpc-io/CY2bRw_P-GY/IGlqRbKHCQAJ

This issue is related to this too: https://github.com/grpc/grpc/issues/7931

**Comment by iSsO** [comment]
Any ETA on when this PR will get accepted?

**Comment by d21d3q** [comment]
It is not ready for accepting.
Lot of things changed since I created this pr. 
Synchronous version is working, but asynchronous not. I will organize it and prepare for merging soon ;)

**Comment by iSsO** [comment]
Great news @d21d3q, can't wait. :)

**Comment by shreyasbharath** [comment]
Any updates @d21d3q ? We are eagerly waiting :)

**Comment by CarlosRDomin** [comment]
Hi @d21d3q, any progress on this? It would be awesome to have gRPC support on nanopb :)

**Comment by Immortalin** [comment]
@d21d3q any updates on this?

**Comment by antegulin** [comment]
@d21d3q This is very exciting, can we expect this merged soon?

**Comment by PetteriAimonen** [comment]
I'm also having less and less time available nowadays, so it is likely that any grpc support for nanopb would have to be maintained as a separate project.

**Comment by d21d3q** [comment]
ok, then I'll move it to separate project.

**Comment by d21d3q** [comment]
Actually I was writing it with aim to use [without http stack](https://github.com/d21d3q/nanopb/tree/e70c8b47c4a3c246bfa3f9dfc48e10c2e5009504/nanogrpc), you can send encoded messages with whataver you want, but this implementation (for now) is above transport layer - it kind of implements http-like messaging.
It is similar to [firmata](https://www.arduino.cc/en/Reference/Firmata)
I what would be your use case? Or what do you expect from something like this?

**Comment by antegulin** [comment]
I'm currently developing a BLE gateway which uses protobuf over MQTT to send data to the cloud.
The BLE gateway could expose a gRPC API for health checks and configuration.

**Comment by PetteriAimonen** [comment]
grpc support based on nanopb is indeed something I'd like to see, but also I'm now quite convinced that it should be maintained as a separate library instead of in the nanopb core.

I'm closing off this pull request for now. @d21d3q If you end up making a separate library of your grpc code, send me a message and I'll add links in nanopb material to it. Also if there are any features in nanopb core that you'd like added to make grpc support easier, let me know.

**Comment by shreyasbharath** [comment]
@d21d3q Are you looking to create a new project `nanogrpc` soon?

**Comment by PetteriAimonen** [comment]
It might also be useful for someone to open discussions on grpc project about adding a C frontend to their main library. From what I understand, the grpc core is already written in C and it already uses nanopb, it is just that there is no C frontend to the library.

Though it might be that the standard grpc core is too large for most microcontrollers, I haven't looked into it.

**Comment by d21d3q** [comment]
Just did it: https://github.com/d21d3q/nanogrpc
You can watch it to stay up to date, by the end of week I will move stuff there.

For now there is synchronous server.

> Though it might be that the standard grpc core is too large for most microcontrollers, I haven't looked into it.

It uses grpc frames to replace http2 layer. I don't know if there exists any http2 library for microcontroller (Arduino?)

**Comment by shreyasbharath** [comment]
@d21d3q From my limited amount of searching, I haven't come across suitable embedded implementations of HTTP2.

I am curious to see which direction your project will go. I think you are on to something.

**Comment by kroggen** [comment]
For ESP32 there are many results, even videos:

https://www.google.com/search?q=esp32+http2

**Pull request closed without merging**
