### PR TITLE
PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ncolomer**
Hi Petteri, 
Your lib is really cool! And it would be great to expose it in [PlatformIO registry](http://platformio.org/#!/lib) :)
Can you merge this manifest file so that PlatformIO is able to reach and register it?

* This library in Web Registry: pending
* Specification: [PlatformIO Library Manager](http://docs.platformio.org/en/latest/librarymanager/index.html)
* Integration: [IDE Integration](http://docs.platformio.org/en/latest/ide.html)

cc @ivankravets

### CODE REVIEW

**Comment by mhaberler** [comment]
cool service - did not know about it!

**Comment by ncolomer** [comment]
@mhaberler @PetteriAimonen Thanks a lot, I just submitted the lib via `platformio lib register` and waiting for approval!

**Comment by ivankravets** [comment]
Thanks @ncolomer !

@PetteriAimonen Could I ask you to merge my pull-request https://github.com/nanopb/nanopb/pull/157 with a few changes?

**Comment by ivankravets** [comment]
Thanks! Library is published in @PlatformIO Regsitry:
- http://platformio.org/#!/lib/show/431/Nanopb

**Pull request merged**
