### PR TITLE
Add C++ message descriptors helper

### PR DESCRIPTION
**Pull request by vlovich**
Zero-overhead. Allows creating simpler general nanopb C++ wrappers by
examining variable type and not needing macro magic.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Hmm, perhaps this should go behind some option. Either on compiler command line, or a message-specific option.

I've been considering moving other rarely used stuff like protoc insertion points behind separate options also, because while they're zero overhead when compiled, they clutter the generates files quite a bit.

**Comment by PetteriAimonen** [comment]
(The travis check fail is also valid: // is not a valid comment in C89, you have to use /* */)

**Comment by vlovich** [comment]
Got it. Will hide it behind a command. Reorganizing can be deferred once you've figured out how you want to organize that stuff?

**Comment by PetteriAimonen** [comment]
Yeah. It wouldn't be any problem for me to add an option for it later, but as this is a new feature it might make sense to have it behind an option to start with.

Otherwise it looks mergeable. I still kind of wish there was a native C++ protobuf library for embedded, but in the absence small helpers like this are useful :)

**Comment by vlovich** [comment]
Well nanopb is a great spot for that :D. Do you have any pointers on how I can write some unit tests for this?

**Comment by PetteriAimonen** [comment]
Well, you can use .cxx files in unittests quite the same way as .c files.
Something quite basic should suffice, i.e. just access the template with the name it should have and check that code compiles and the values returned are correct. Doesn't even have to encode or decode anything. The "enum_to_string" testcase might be a reasonable template, it also tests just a few simple functions.

As for enabling the option, use NANOPBFLAGS variable in SConscript: https://github.com/nanopb/nanopb/blob/master/tests/regression/issue_203/SConscript

**Comment by vlovich** [comment]
That doesn't seem to work. The test runs with both environments appended to each other

**Comment by vlovich** [comment]
--nanopb_out=--cpp-descriptor--strip-path:.

**Comment by vlovich** [comment]
NVM. Figured it out.

**Comment by vlovich** [comment]
OK. I made some more changes vs the last thing you reviewed:

1. Hide the descriptor behind namespace nanopb
2. Add support for C++ versions between C++03 & C++17
3. Add tests for C++03, C++11, C++14, & C++17 versions of the generated code (maybe there's a cleaner way you'd like me to do it?
4. Fix regression 203 SConscript to not adjust the global env.

**Comment by PetteriAimonen** [comment]
Hmm yeah, looks good otherwise than the duplication of code in the tests.

Perhaps it could be done in single SConscript like this:

     env_cpp03 = env.Clone()
     env_cpp03.Append(CXXFLAGS = '-std=c++11')
     p = env_cpp03.Program('test_cpp03', ['message_descriptor.cc', 'message.pb.c'])
     env_cpp03.Run(p)
     
     env_cpp11 = env.Clone()
     env_cpp11.Append(CXXFLAGS = '-std=c++11')
     p = env_cpp03.Program('test_cpp11', ['message_descriptor.cc', 'message.pb.c'])
     env_cpp11.Run(p)

So that the source code doesn't need to be duplicated. Easier to add extra checks later.

**Comment by vlovich** [comment]
Sounds good.

**Comment by vlovich** [comment]
Not familiar enough with scons. How do I modify my PR to skip if the compiler doesn't support the flag?

I tried
```
    e.Append(CXXFLAGS = '-std={}'.format(std))

    conf = Configure(e)
    if not conf.CheckCXX():
        print("Skipping {} test - compiler doesn't support it".format(std))
        continue
```

but then SCons just exits with an error but no message about what I'm doing wrong:
```
Checking whether the C++ compiler works... yes

scons: *** 
```

**Comment by vlovich** [comment]
Hacked something together that works - not sure if that's the cleanest way to write it. Let me know.

**Comment by PetteriAimonen** [comment]
Thanks, merged!

**Pull request merged**
