### PR TITLE
Fix Command Generator Location of Simple Example 

### PR DESCRIPTION
**Pull request by walidamriou**
This pull request addresses the issue of the command generator location. 

The change involves updating the command used for code generation from `../../generator-bin/protoc --nanopb_out=. simple.proto` to ` ../../generator/protoc --nanopb_out=. simple.proto` .

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Which platform is this for? Considering the makefile works for Linux (and OS X, BSD etc. even though readme doesn't say that) directly.

On Windows I guess it will work, if there is a suitable Python installation with necessary packages. Otherwise the binary package would be easier on Windows.

**Comment by walidamriou** [comment]
This update effect README.txt only, the path of protoc is ` ../../generator/protoc --nanopb_out=. simple.proto `not  `../../generator-bin/protoc --nanopb_out=. simple.proto` in **examples/simple/README.txt** 

Tested in Windows

**Comment by PetteriAimonen** [comment]
In the Windows binary packages, there is `generator-bin/protoc` instead. But yeah, it's not clear which would be better in the README.

**Comment by walidamriou** [comment]
It's perfectly fine now. This is what I observed when using the master branch directly. 

It's possible that if I use the Windows binary packages, the experience might be different.

**Pull request closed without merging**
