### PR TITLE
Implement conan recipe

### LINKED ISSUE #294: Publish Conan package
If you haven't heard of [Conan](https://www.conan.io/), it's a C/C++ package manager that is gaining a lot of popularity.

I think it'd be great if every release of Nano Protocol Buffers was automatically published as a new version of a Conan package. It'll make consuming it in other projects really easy, and also updating to newer versions.

### PR DESCRIPTION
**Pull request by amatosov-rbx**
Fixes #294

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
How should `version = "0.3.9.2"` be handled?

It seems like it should be 0.4.0-dev in the master now, and `tools/set_version.sh` should be changed to update also that recipe.

**Comment by amatosov-rbx** [comment]
good point. I'll fix that

**Comment by PetteriAimonen** [comment]
(The failing check is just due to travis having some download troubles again.)

**Comment by amatosov-rbx** [comment]
I've pushed version patching in `set_version.sh`, tested it with gnu-sed on macOS and it patches all files properly.

**Comment by PetteriAimonen** [comment]
Thanks!

**Pull request merged**
