### PR TITLE
Rename 'proto' to 'nanopb_proto'

### LINKED ISSUE #845: The Criterion project is broken after nanopb upgrade to 0.4.7
https://github.com/Snaipe/Criterion

```
===>  Building for criterion-2.4.1
[  1% 1/51] /usr/ports/devel/criterion/work/Criterion-2.4.1/src/protocol/gen-pb.py /usr/local/bin/protoc /usr/local/bin/protoc-gen-nanopb ../src/protocol/criterion.proto ../src/protocol/criterion.options /usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src
FAILED: src/criterion.pb.c src/criterion.pb.h 
/usr/ports/devel/criterion/work/Criterion-2.4.1/src/protocol/gen-pb.py /usr/local/bin/protoc /usr/local/bin/protoc-gen-nanopb ../src/protocol/criterion.proto ../src/protocol/criterion.options /usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src
/usr/local/bin/protoc --plugin=protoc-gen-nanopb=/usr/local/bin/protoc-gen-nanopb -I../src/protocol --nanopb_out=-f ../src/protocol/criterion.options:/usr/ports/devel/criterion/work/Criterion-2.4.1/_build/src ../src/protocol/criterion.proto
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-nanopb", line 7, in <module>
    from nanopb_generator import *
  File "/usr/local/bin/nanopb_generator.py", line 55, in <module>
    from proto import TemporaryDirectory
ImportError: cannot import name 'TemporaryDirectory' from 'proto' (unknown location)
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by paolostivanin**
This fixes #845 and allows [proto-plus-python](https://github.com/googleapis/proto-plus-python)  to be installed on the system without causing any conflict with nanopb.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
I'm not sure I like this.

I think it would be better to have one common structure of Python packaging of nanopb, namely, the way `pip install nanopb` does it currently: installs as a package called `nanopb`.

**Comment by paolostivanin** [comment]
you mean changing `nanopb_proto` to `nanopb`?

**Comment by PetteriAimonen** [comment]
No. Instead of renaming any of the source directories, build up the directory structure in CMake installation.

**Comment by paolostivanin** [comment]
ah ok, got it! I'll look into it

**Comment by PetteriAimonen** [comment]
I think to start with, it would be useful if you can add a GitHub workflow to run some tests on the CMake and Conan installation methods. When they are totally untested, they'll just keep breaking with future releases.

**Pull request closed without merging**
