### PR TITLE
Escape Python path (solve issue with a space)

### PR DESCRIPTION
**Pull request by ivankravets**
Related issue https://github.com/platformio/platformio-core/issues/4467

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Thanks!

I'll merge this. There may be some remaining issues, considering pull requests #808 and #809, but the latter is not in a mergeable state and I haven't had time to look at it.

**Comment by ivankravets** [comment]
@Saad-Mufti, could change temporarily your `platformio.ini` to 

```
lib_deps = 
    https://github.com/nanopb/nanopb.git
```

and remove `.pio` folder from the project. Does it build well now?

**Comment by Saad-Mufti** [comment]
It does not seem to have been fixed. I also went ahead and removed `protobuf` from the `.pio` Python installation, and ran `pio run -v`:

```
Processing teensy41 (platform: teensy; board: teensy41; check_tool: cppcheck; framework: arduino; lib_deps: https://github.com/nanopb/nanopb.git, featherfly/SoftwareSerial@^1.0, SPI, https://github.com/basicmicro/roboclaw_arduino_library.git, https://github.com/whackamadoodle3000/SOLO-motor-controllers-ARDUINO-library-Teensy4.1-Compatible; custom_nanopb_protos: 
+<protos/urc.proto>)
--------------------------------------------------------------------------------------------------------------------------------------
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensy41.html
PLATFORM: Teensy (4.17.0) > Teensy 4.1
HARDWARE: IMXRT1062 600MHz, 512KB RAM, 7.75MB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES: 
 - framework-arduinoteensy @ 1.157.220801 (1.57) 
 - tool-teensy @ 1.157.0 (1.57) 
 - toolchain-gccarmnoneeabi @ 1.50401.190816 (5.4.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
"C:\Users\Saad Mufti\.platformio\penv\Scripts\python.exe" -m pip install "protobuf>=3.19.1"
Collecting protobuf>=3.19.1
  Downloading protobuf-4.21.10-cp39-cp39-win_amd64.whl (525 kB)
     ------------------------------------- 525.5/525.5 kB 11.0 MB/s eta 0:00:00
Installing collected packages: protobuf
Successfully installed protobuf-4.21.10

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
[nanopb] Processing 'protos\<abc>.proto' (no options)
C:\Users\Saad Mufti\.platformio\penv\Scripts\python.exe D:\GitHub\urc-firmware\.pio\libdeps\teensy41\Nanopb\generator\..\generator\nanopb_generator.py --output-dir=D:\<Project-Root>\.pio\build\teensy41\nanopb\generated-src --proto-path=D:\<protos-path>\protos <abs>.proto
'C:\Users\Saad' is not recognized as an internal or external command,
operable program or batch file.
[nanopb] ERROR: (1) processing cmd: '['$PYTHONEXE', 'D:\\Project-Root\\.pio\\libdeps\\teensy41\\Nanopb\\generator\\..\\generator\\nanopb_generator.py', '--output-dir=D:\\Project-Root\\.pio\\build\\teensy41\\nanopb\\generated-src', '--proto-path=D:\\Project-Root\\protos', 'urc.proto']'
*** Error 1
===================================================== [FAILED] Took 7.18 seconds =====================================================

```

**Comment by ivankravets** [comment]
@hacker-cb, could you provide a PR that fixes the issue with spaces? If you call Python script before "PlatformIO runs", you can use native Python's `subprocess.run` instead of SCons' env.Execute and pass arguments as "list". Python will automatically handle spaces in arguments.

**Comment by PetteriAimonen** [comment]
@Saad-Mufti Can you retry now? (may need `pio lib update`)

**Comment by hacker-cb** [comment]
@ivankravets fixed in https://github.com/nanopb/nanopb/pull/839

**Comment by ivankravets** [comment]
Sorry that I didn't specify the details. I meant these lines https://github.com/nanopb/nanopb/blob/master/generator/platformio_generator.py#L137:L139

PR #839 actually duplicates this PR and I recommend to revert #839. I like more verbose action. What we need is to fix  https://github.com/nanopb/nanopb/blob/master/generator/platformio_generator.py#L137:L139

P.S.: Sorry, I'm a macOS user and can't reproduce this issue.

**Comment by hacker-cb** [comment]
@ivankravets may this should be ALSO fixed, not INSTEAD?
i guess behavior should be the same in all python calls if it has spaces in paths?

**Comment by ivankravets** [comment]
It is up to you. Both variants do the same job. Please do it as it is easy to maintain for you.

**Comment by PetteriAimonen** [comment]
I think I might have fixed those lines already in commit [2d50640](https://github.com/nanopb/nanopb/commit/2d506406fb039dd6ed732abf26c2f62e0c70c5f9) above, as it was a regression caused by https://github.com/nanopb/nanopb/commit/160be3f383ad56d25806647ea4dea6dccf99af80.

But I haven't tested on Windows.

**Comment by ivankravets** [comment]
The https://github.com/nanopb/nanopb/commit/2d506406fb039dd6ed732abf26c2f62e0c70c5f9 commit does not solve the problem. It is actually the same. When SCons calls `"$PYTHONEXE"` it automatically expands dynamic variables.

I found the draft of PR that should fix this issue https://github.com/nanopb/nanopb/pull/809

Instead of `--nanopb_out="/` lines, we can use 

```python
import subprocess

args = [env.subst("$PYTHONEXE"), "--nanopb_out", _VALUE_, "--nanopb_opt", "--error-on-unmatched", ...]

subprocess.run(args)

```

Python will automatically escape values that contain a space symbol.

Hope this hint will help to fix this issue.

**Comment by PetteriAimonen** [comment]
@ivankravets Have you actually tested that it does not solve the problem, or is this just based on code review?
For me it works on Windows now (using `lib_deps = nanopb = https://github.com/nanopb/nanopb.git`), even when my user name has spaces in it.

The difference that 2d50640 makes is that when scons expands `"$PYTHONEXE"`, it tries to be helpful by splitting it at spaces, as if it was a list of command arguments instead of a single path. By expanding it before list construction it should stay in one piece.

**Comment by Saad-Mufti** [comment]
I'm not seeing any more errors with the space in my user path anymore; it looks like its fixed!

Thank you all for your help!

**Comment by PetteriAimonen** [comment]
@Saad-Mufti Thanks for testing!

**Pull request merged**
