### PR TITLE
C style (WIP)

### PR DESCRIPTION
**Pull request by td-krzysiek**
Hi,

I've started to work on a pull request for #199 / #533. I would like to check if this is heading into the right direction, do you have any comments? I added a simple example `examples/c_style` to show generated code.

Kind regards,
Krzysztof

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
In a brief look, the generator side code changes look mostly reasonable.
I would suggest renaming `StyleDefault` to `NamingStyle` and then have `NamingStyleC` inherit from that, overriding the methods.
In that way there would be a common base class which can be useful for future maintenance.

The automatic tests detect some errors which must be fixed.

Also this feature will need an automatic test under e.g. `tests/namingstyle`.
This could have a proto file that has all the different element types, and then a C file that references them. If the reference by C names compiles, the feature works.
E.g. `test/typename_mangling` test case has similar structure.

**Comment by td-krzysiek** [comment]
Thinking of this a bit longer, cli argument probably makes sense. This feature should be enabled for the entire code generation process, rather than enabled / disabled for certain fields etc.

**Comment by PetteriAimonen** [comment]
Command line argument does make sense with the way the pull request code is currently made.
A per-file or per-message option could make sense also, but that would be more difficult to implement.

**Comment by td-krzysiek** [comment]
Hi @PetteriAimonen,

I think this is now ready for a review, I still might have missed some flags or combination of flags which will break the code but I tried to cover most use cases. If you have idea what other options I can try, I'm happy to add this to the test case.

I wasn't able to change `*_MSGTYPE` defines to capital letters, these are merged internally with struct name in `PB_BIND` macro, and I don't want to touch `pb.h` in this commit. Hopefully this is still fine.

Let me now if you have comments or suggestion.

**Comment by PetteriAimonen** [comment]
Yeah, `_MSGTYPE` will have to remain as is, because it has to match the struct name. But they are mostly for internal use anyway.

I'll try to find time to review in more detail in the next few days.

**Comment by rosek86** [comment]
Thank you!

**Comment by PetteriAimonen** [comment]
Thanks, this is merged now!

I decided to remove the example, because it didn't add much compared to the existing examples, so I felt it was just unnecessary maintenance burden.

**Pull request closed without merging**
