### PR TITLE
ref |> Modified The generated code uses utf-8 encoding by default.

### PR DESCRIPTION
**Pull request by xiaoyu-ebox**
Avoid garbled code generated when annotating proto in Chinese or other languages.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Which Python version are you using? I think unicode should already be default for Python3.

**Comment by PetteriAimonen** [comment]
Hmm, actually depends on locale  https://stackoverflow.com/questions/36303919/what-encoding-does-open-use-by-default  so makes sense to force utf-8.

**Comment by PetteriAimonen** [comment]
Seems to work well in my tests on both Python2 and Python3, thanks!

**Comment by xiaoyu-ebox** [comment]
> 

I am using python3, which should be related to the windows system native language.

**Comment by xiaoyu-ebox** [comment]
Thank you very much for this project. It helps me. Thank you.

**Pull request merged**
