### PR TITLE
Enums: add a validation function

### PR DESCRIPTION
**Pull request by jaskij**
As I wrote in #988 , adding an enum validation function is a feature I'd find useful.

The one big question I have is the type of argument the function should take. Should it be the type of enum used, or should it be some integer type?

Marking as draft until I add tests.

### CODE REVIEW

**Comment by jaskij** [comment]
The basic stuff should be done.

One more question: I see `enum_to_string` tested in the `namingstyle` test. Should I add something with `enum_validate` too?

**Comment by PetteriAimonen** [comment]
Yeah, I think it would be good to have a test for naming style too, the name mangling sometimes has surprising bugs.

Other than that, looks ready to merge.

**Comment by jaskij** [comment]
This should cover it?

Also, obvious caveat: this only checks if the integer value is a valid member of the enum, so it can throw a curveball, like in the naming style this passed.

```c
my_enum2_valid(ME_ENUM1_ENTRY_FIRST) == true
```

**Comment by PetteriAimonen** [comment]
Thanks!

**Pull request merged**
