### PR TITLE
make the default fallback strategy for FT_DEFAULT configurable

### PR DESCRIPTION
**Pull request by ConradWood**
As discussed here:

https://github.com/nanopb/nanopb/issues/772#issuecomment-1094100183

Note: testsuite ran and completed successfully.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Thanks! Are you interested in adding a test case for this also? It could go in `tests/options`.

**Comment by ConradWood** [comment]
tbh not keen - python isn't my first or preferred environment.
But I see the value and need, so I will have a go at it.

**Comment by PetteriAimonen** [comment]
Thanks, if you get stuck just let me know and I'll see about it. Should only need to add usage tests of the new option to `options.proto` and then in `options_h.expected` the pattern in `.pb.h` file that should be checked for.

**Comment by ConradWood** [comment]
I added the test case for fallback_type now.
Would you kindly consider it for inclusion again?

**Comment by ConradWood** [comment]
The scons version on debian (my environment) passed the test, but not on the ubuntu workflow. I believe the latest patch fixes this, albeit I did not verify this on ubuntu. Please trigger the workflow again

**Comment by PetteriAimonen** [comment]
Thanks!

**Comment by ConradWood** [comment]
Thank you!

On 13 April 2022 10:00:05 WEST, Petteri Aimonen ***@***.***> wrote:
>Thanks!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nanopb/nanopb/pull/773#issuecomment-1097745171
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
