### PR TITLE
change generator to raise error on unmatched options and add cli option to disable

### LINKED ISSUE #456: nanopb continues to compile if options have unmatched fields
`Following patterns in <filename>.options did not match any fields: <list of field names>`

If you specify options on a certain field name, and the generator cannot find it, it will print the above message, however the compilation process continues and files are still produced. I believe the correct behaviour should be for the process to terminate after that error message. If someone were to rename a field in their .proto file, and forget to do the equivalent rename in their .optiosn file, they would still get a compiled output, but with incorrect options.

### PR DESCRIPTION
**Pull request by wmmc88**
closes #456

### CODE REVIEW

**Comment by wmmc88** [comment]
@PetteriAimonen  I fixed one of the tests, but im not sure why the name mangling tests fail. It should be able to pick up those fields, so i'm not sure why it doesn't.

**Comment by PetteriAimonen** [comment]
Please make it off by default.

I value backwards compatibility a lot, and this has the potential to break otherwise working builds.

**Comment by wmmc88** [comment]
updated the default behaviour to be backwards compatible

**Comment by PetteriAimonen** [comment]
Great, thanks!

**Comment by wmmc88** [comment]
Will this be part of 0.4.0 or after that?

**Comment by PetteriAimonen** [comment]
It will go in 0.4.0, once I get around to releasing it.

**Pull request merged**
