### PR TITLE
Remove `nocopts` from cc_nanopb_proto_library

### PR DESCRIPTION
**Pull request by armandomontanez**
With Bazel 7.0.0, nocopts has been removed and is no longer supported.
The correct way to handle this is to subtract features using the
`features` attribute (see bazelbuild/bazel#8706).

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
@silvergasp Do you want to take a look?

**Comment by silvergasp** [comment]
Yeah LGTM

**Comment by armandomontanez** [comment]
It seems I don't have necessary permissions to merge, can someone hit the button for me?

**Comment by silvergasp** [comment]
I don't have write permissions either. @PetteriAimonen does, I just review these as I wrote the original Bazel rules.

**Comment by PetteriAimonen** [comment]
Yeah, I was sleeping :)
Thanks everyone!

**Comment by armandomontanez** [comment]
Thanks! 😁

**Pull request merged**
