### PR TITLE
run binary_packages on Python 3.8, and on latest 3.x

### PR DESCRIPTION
**Pull request by jaskij**
Due to #887 , it occurred to me it may be a good idea to test on the latest version of Python as well, among others to get early warnings of deprecations.

### CODE REVIEW

**Comment by jaskij** [comment]
@PetteriAimonen I managed to reproduce #887 in CI, and it rightfully causes the CI to fail. Do you want me to create a new PR with both this repro and the proposed solution from #994 ? Or how do you want me to proceed?

**Comment by PetteriAimonen** [comment]
Yes, I think the CI test from this pull request and the fix from #994 would be good. I don't think the `check_pkg_resources.sh` is necessary if the CI build now catches this.

**Comment by jaskij** [comment]
No, it won't be. That script was a workaround for CI not catching this.

**Comment by jaskij** [comment]
@lubosz can you review the changes? It seems to be working now, but I'm not familiar enough with Python to be sure.

From what I read, this should work in the general case, but there may be some weird edge case with grpcio-tools being installed as an archive that I missed.

[CI run](https://github.com/nanopb/nanopb/actions/runs/10015300359/job/27686494415) showing that it does indeed catch #887

**Comment by jaskij** [comment]
I talked the changes through with someone who has Python experience off GitHub, and he agreed this will work. The only breakage that could happen, which wouldn't with `pkg_resources` would be if `grpcio-tools` changes the way it's shipped, and it shomehow is an archive. Which is unlikely, and should be quickly caught by CI anyway.

**Comment by PetteriAimonen** [comment]
Thanks a lot!

**Pull request merged**
