### PR TITLE
Introduce new compile time flag: PB_VALIDATE_UTF8

### PR DESCRIPTION
**Pull request by prusnak**
Check whether incoming strings are valid UTF-8 sequences. Slows down the string processing slightly and slightly increases code size.

### CODE REVIEW

**Comment by PetteriAimonen** [comment]
Hmm, I wonder if perhaps a less fast but smaller code size algorithm might be desirable. After all nanopb trades speed for size elsewhere also. Particularly on AVR, the array will go in RAM.

But even as it is, I'm ok with merging this once you consider it finished. After all it is usable for most platforms and an optional feature.

**Comment by prusnak** [comment]
I changed the implementation to the one which does not use look-up table. Hopefully this better matches the goals of nanopb. Also I marked the PR as "ready to review" (i.e. it's not in draft anymore).

**Comment by PetteriAimonen** [comment]
Looks good, thanks! I'll eventually add a few unittests for failing utf-8 cases also, but I can do that myself.

**Comment by prusnak** [comment]
Cool, I wanted to add failing cases for unit tests, but it was not obvious to me how to add them. It would great if you added them! Thanks!

**Pull request merged**
